version: '3.8'

services:
  budget-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: budget-tracker-app
    ports:
      - "3000:3000"
    volumes:
      # Persist the SQLite database
      - budget_data:/app/database
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  # Named volume to persist database data
  budget_data:
    driver: local
